version: "3.5"

services:

  mongo-server1:
    image: mongo
    container_name: mongoserver1
    command: mongod --replSet mongo-replica --bind_ip_all --port 27017 --dbpath /data/db --keyFile /data/replica.key
    volumes:
      - $PWD/mongodb-keyfile:/data/replica.key
      - mongo1_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-server2:
    image: mongo
    container_name: mongoserver2
    command: mongod --replSet mongo-replica --bind_ip_all --port 27017 --dbpath /data/db --keyFile /data/replica.key
    volumes:
      - $PWD/mongodb-keyfile:/data/replica.key
      - mongo2_db:/data/db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example      
  mongo-server3:
    image: mongo
    container_name: mongoserver3
    command: mongod --replSet mongo-replica --bind_ip_all --port 27017 --dbpath /data/db --keyFile /data/replica.key
    volumes:
      - $PWD/mongodb-keyfile:/data/replica.key
      - mongo3_db:/data/db
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongo1_db:
  mongo2_db:
  mongo3_db: